import { z } from "zod";

export const IPC_CHANNELS = {
  appBootstrap: "app:get-bootstrap",
  shellOpenExternal: "shell:open-external",
  shellRevealPath: "shell:reveal-path",
  dialogConfirm: "dialog:confirm",
  dialogMessage: "dialog:message",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  filePick: "file:pick",
  fileSaveText: "file:save-text",
  fileReadImage: "file:read-image",
  fileListWorkspace: "file:list-workspace",
  fileReadWorkspace: "file:read-workspace",
  accountSessionGet: "account-session:get",
  accountSessionSet: "account-session:set",
  accountSessionClear: "account-session:clear",
  workspaceList: "workspace:list",
  workspaceAdd: "workspace:add",
  workspaceUpdate: "workspace:update",
  workspaceRemove: "workspace:remove",
  workspaceConnect: "workspace:connect",
  workspaceIsDirectory: "workspace:is-directory",
  workspacePick: "workspace:pick",
  agentGetStatus: "agent:get-status",
  agentGetEvents: "agent:get-events",
  agentEvent: "agent:event",
  agentListThreads: "agent:list-threads",
  agentStartThread: "agent:start-thread",
  agentResumeThread: "agent:resume-thread",
  agentUnsubscribeThread: "agent:unsubscribe-thread",
  agentStartTurn: "agent:start-turn",
  agentSteerTurn: "agent:steer-turn",
  agentInterruptTurn: "agent:interrupt-turn",
  agentRespondServerRequest: "agent:respond-server-request",
  agentModelList: "agent:model-list",
  agentConfigRead: "agent:config-read",
  agentCollaborationModeList: "agent:collaboration-mode-list",
  agentSkillsList: "agent:skills-list",
  agentAppsList: "agent:apps-list",
  agentAccountRead: "agent:account-read",
  agentAccountRateLimitsRead: "agent:account-rate-limits-read",
  agentThreadRead: "agent:thread-read",
  agentThreadArchive: "agent:thread-archive",
  agentThreadNameSet: "agent:thread-name-set",
  browserCreateTab: "browser:create-tab",
  browserListTabs: "browser:list-tabs",
  browserNavigate: "browser:navigate",
  browserControl: "browser:control",
  browserTakeControl: "browser:take-control",
  browserRespondPermission: "browser:respond-permission",
  browserRespondSensitiveAction: "browser:respond-sensitive-action",
  browserResolveDownload: "browser:resolve-download",
  browserRespondDialog: "browser:respond-dialog",
  browserResolveFileChooser: "browser:resolve-file-chooser",
  browserCloseTab: "browser:close-tab",
  browserSetLayout: "browser:set-layout",
  browserTabsChanged: "browser:tabs-changed",
} as const;

export const BootstrapInfoSchema = z.object({
  version: z.string().min(1),
  platform: z.enum(["win32", "darwin", "linux"]),
  windowGeneration: z.number().int().positive(),
});

export type BootstrapInfo = z.infer<typeof BootstrapInfoSchema>;
