import { z } from "zod";

export const IPC_CHANNELS = {
  appBootstrap: "app:get-bootstrap",
  appInitialize: "app:initialize",
  appRetry: "app:retry",
  appExportDiagnostics: "app:export-diagnostics",
  shellOpenExternal: "shell:open-external",
  shellRevealPath: "shell:reveal-path",
  dialogConfirm: "dialog:confirm",
  dialogMessage: "dialog:message",
  menuPopup: "menu:popup",
  menuSetAccelerators: "menu:set-accelerators",
  systemUiEvent: "system-ui:event",
  traySetRecentThreads: "tray:set-recent-threads",
  traySetSessionUsage: "tray:set-session-usage",
  notificationShow: "notification:show",
  updateCheck: "update:check",
  updateDownload: "update:download",
  updateInstall: "update:install",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  filePick: "file:pick",
  fileSaveText: "file:save-text",
  fileReadImage: "file:read-image",
  fileListWorkspace: "file:list-workspace",
  fileReadWorkspace: "file:read-workspace",
  fileWriteWorkspace: "file:write-workspace",
  accountSessionGet: "account-session:get",
  accountSessionSet: "account-session:set",
  accountSessionClear: "account-session:clear",
  workspaceList: "workspace:list",
  workspaceAdd: "workspace:add",
  workspaceUpdate: "workspace:update",
  workspaceRemove: "workspace:remove",
  workspaceConnect: "workspace:connect",
  workspaceIsDirectory: "workspace:is-directory",
  workspacePick: "workspace:pick",
  gitStatus: "git:status",
  gitInit: "git:init",
  gitCreateRepository: "git:create-repository",
  gitRoots: "git:roots",
  gitDiffs: "git:diffs",
  gitLog: "git:log",
  gitCommitDiff: "git:commit-diff",
  gitRemote: "git:remote",
  gitStageFile: "git:stage-file",
  gitStageAll: "git:stage-all",
  gitUnstageFile: "git:unstage-file",
  gitRevertFile: "git:revert-file",
  gitRevertAll: "git:revert-all",
  gitCommit: "git:commit",
  gitPush: "git:push",
  gitPull: "git:pull",
  gitFetch: "git:fetch",
  gitSync: "git:sync",
  gitBranches: "git:branches",
  gitCheckoutBranch: "git:checkout-branch",
  gitCreateBranch: "git:create-branch",
  gitIssues: "git:issues",
  gitPullRequests: "git:pull-requests",
  gitPullRequestDiff: "git:pull-request-diff",
  gitPullRequestComments: "git:pull-request-comments",
  gitCheckoutPullRequest: "git:checkout-pull-request",
  terminalOpen: "terminal:open",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalClose: "terminal:close",
  terminalEvent: "terminal:event",
  agentGetStatus: "agent:get-status",
  agentGetEvents: "agent:get-events",
  agentEvent: "agent:event",
  agentListThreads: "agent:list-threads",
  agentStartThread: "agent:start-thread",
  agentResumeThread: "agent:resume-thread",
  agentUnsubscribeThread: "agent:unsubscribe-thread",
  agentStartTurn: "agent:start-turn",
  agentSteerTurn: "agent:steer-turn",
  agentInterruptTurn: "agent:interrupt-turn",
  agentReviewStart: "agent:review-start",
  agentExperimentalFeatureList: "agent:experimental-feature-list",
  agentExperimentalFeatureSet: "agent:experimental-feature-set",
  agentThreadFork: "agent:thread-fork",
  agentThreadCompact: "agent:thread-compact",
  agentThreadRollback: "agent:thread-rollback",
  agentMcpServerStatusList: "agent:mcp-server-status-list",
  agentRespondServerRequest: "agent:respond-server-request",
  agentModelList: "agent:model-list",
  agentConfigRead: "agent:config-read",
  agentCollaborationModeList: "agent:collaboration-mode-list",
  agentSkillsList: "agent:skills-list",
  agentAppsList: "agent:apps-list",
  agentAccountRead: "agent:account-read",
  agentAccountRateLimitsRead: "agent:account-rate-limits-read",
  agentAccountLoginStart: "agent:account-login-start",
  agentAccountLoginCancel: "agent:account-login-cancel",
  agentAccountLogout: "agent:account-logout",
  agentThreadRead: "agent:thread-read",
  agentThreadArchive: "agent:thread-archive",
  agentThreadNameSet: "agent:thread-name-set",
  browserCreateTab: "browser:create-tab",
  browserListTabs: "browser:list-tabs",
  browserNavigate: "browser:navigate",
  browserControl: "browser:control",
  browserTakeControl: "browser:take-control",
  browserRespondPermission: "browser:respond-permission",
  browserRespondSensitiveAction: "browser:respond-sensitive-action",
  browserResolveDownload: "browser:resolve-download",
  browserRespondDialog: "browser:respond-dialog",
  browserResolveFileChooser: "browser:resolve-file-chooser",
  browserCloseTab: "browser:close-tab",
  browserSetLayout: "browser:set-layout",
  browserTabsChanged: "browser:tabs-changed",
} as const;

export const BootstrapInfoSchema = z.object({
  version: z.string().min(1),
  platform: z.enum(["win32", "darwin", "linux"]),
  windowGeneration: z.number().int().positive(),
  runtime: z.object({
    phase: z.enum(["idle", "initializing", "ready", "unauthenticated", "degraded"]),
    attempt: z.number().int().nonnegative(),
    codexHomeId: z.string().regex(/^[a-f0-9]{16,64}$/),
    error: z.string().max(512).nullable(),
  }),
});

export type BootstrapInfo = z.infer<typeof BootstrapInfoSchema>;

export const RuntimeBootstrapStatusSchema = BootstrapInfoSchema.shape.runtime;
export type RuntimeBootstrapStatus = z.infer<typeof RuntimeBootstrapStatusSchema>;

export const DiagnosticsExportSchema = z.object({
  defaultFileName: z.string().min(1).max(255),
  content: z.string().max(8 * 1024 * 1024),
});
export type DiagnosticsExport = z.infer<typeof DiagnosticsExportSchema>;
